name: Build kubecfg

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, macos, windows]
        include:
          - build: linux
            os: ubuntu-latest
            name: kubecfg
          - build: macos
            os: macos-latest
            name: kubecfg
          - build: windows
            os: windows-latest
            name: kubecfg.exe
      fail-fast: false

    steps:
      - name: Setup
        run: rustup override set stable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --verbose --release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: kubecfg-${{ matrix.build }}
          path: target/release/${{ matrix.name }}
          overwrite: true
